name: Run PHPUnit Tests

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'cli.php'
      - 'composer.json'
      - 'composer.lock'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'cli.php'
      - 'composer.json'
      - 'composer.lock'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPUnit
        run: vendor/bin/phpunit
